apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: icc-haedong-reservation-prod
resources:
- namespace.yaml
- secret.yaml
- ../../base
patches:
- path: domain.json
  target:
    kind: Ingress
    name: icc-haedong-reservation-ingress
images:
- name: scgskku/icc-haedong-seminar-reservation
  newTag: 4a39ab906852415e7051c7d7ba660fdab166d22d
