apiVersion: v1
kind: Secret
metadata:
  name: icc-haedong-reservation-secret
type: Opaque
data:
  APP_PORT: <path:kv/data/icc-haedong-seminar#port | base64encode>
  SESSION_SECRET: <path:kv/data/icc-haedong-seminar#session-secret | base64encode>
  RECAPTCHA_PUBLIC_KEY: <path:kv/data/icc-haedong-seminar#recaptcha-public | base64encode>
  RECAPTCHA_PRIVATE_KEY: <path:kv/data/icc-haedong-seminar#recaptcha-private | base64encode>
  DB_HOST: <path:kv/data/icc-haedong-seminar#db-host | base64encode>
  DB_USER: <path:kv/data/icc-haedong-seminar#db-user | base64encode>
  DB_USERNAME: <path:kv/data/icc-haedong-seminar#db-username | base64encode>
  DB_PASSWORD: <path:kv/data/icc-haedong-seminar#db-password | base64encode>
  DB_NAME: <path:kv/data/icc-haedong-seminar#db-database | base64encode>
  DB_DIALECT: <path:kv/data/icc-haedong-seminar#dialect | base64encode>
  DB_PORT: <path:kv/data/icc-haedong-seminar#db-port | base64encode>
  DB_LOGGING: <path:kv/data/icc-haedong-seminar#logging | base64encode>
  DB_MULTIPLE_STATEMENTS: <path:kv/data/icc-haedong-seminar#multipleStatements | base64encode>
  DB_TIMEZONE: <path:kv/data/icc-haedong-seminar#timezone | base64encode>